categories: 分类
search: 搜索
tags: 标签
tagcloud: Tag Cloud
prev: 上一页
next: 下一页
comment: Comments
contents: 目录
archive_a: 归档
archive_b: "Archives: %s"
archive_date: "MMM YYYY"
page: Page %d
recent_posts: Recent Posts
menu: Menu
weibo: Weibo
links: 相关链接
rss: RSS
doubanshow: Douban Show
github-card: Github Card
showsidebar: 显示边栏
hidesidebar: 隐藏边栏
updated: Updated
totop: 返回顶部
datepublished: 发表于
